Here we are going to see why numpy arrays are faster when compared to python list and why in terms of speed and memory


In [2]:

a = [i for i in range(10000000)];
b = [i for i in range(10000000,20000000)];
c = [];
import time;
start = time.time();
for i in range(len(a)):
    c.append(a[i] + b[i]);

print(time.time() - start);







2.0453171730041504


In [3]:
import numpy as np;
a = np.arange(10000000);
b = np.arange(10000000,20000000);
start = time.time();
c = a + b;
print(time.time() - start);


0.14814090728759766


In [4]:
2.04/0.14
 ## So with this we can confirm that numpy arrays are way faster than the lists because of their fixed size
 ## in memory where as list are dynamic arrays and the references are stored not the arrays as continous blocks so to access and do computations on them it takes time

14.571428571428571

In [8]:
## seeing in terms of memory both the list and numpy arrays how much space does they take on the RAM
a = [i for i in range(10000000)];
import sys 
print(sys.getsizeof(a));
b = np.arange(10000000,dtype = np.int32);
c = np.arange(10000000,dtype = np.int16);
print(sys.getsizeof(b));
print(sys.getsizeof(c));

89095160
40000112
20000112


In [9]:
## In the previous class we had seen indexing and slicing now we will see adv Indexing
## Fancy Indexing it is nothing but we cant always find the patterns for rows and columns to get the desired elements so we use this
a = np.arange(24).reshape(6,4);
print(a);


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [17]:
##Now i need to print 0,1,3,4,5 rows to get printed for me now there is no pattern for doing this
print(a[[0,1,3,4,5]]);
## Now i need only only first second and last cols not all
print(a[[0,1,3,4,5],[0,1,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (5,) (3,) 

In [20]:
## Another type of indexing Boolean indexing here we get those elements/items from the array that satisfy the given condition
a = np.random.randint(1,100,24).reshape(4,6);
print(a);
print(a > 20);

[[12  4 89 81 87 49]
 [93 29 13 27 67 43]
 [17 22 90 46 12 51]
 [50 65 72 14  4 38]]
[[False False  True  True  True  True]
 [ True  True False  True  True  True]
 [False  True  True  True False  True]
 [ True  True  True False False  True]]


In [ ]:
## We need to get those elements from the array which are greater than 20
print(a[a > 20]);
## here we use the boolean masking and get only those particular elements that satisfy the condition and the result is in the form of 1D Array


[89 81 87 49 93 29 27 67 43 22 90 46 51 50 65 72 38]


In [23]:
## Find all the numbers greater than 50 and are even
print(a[(a > 50) & (a % 2 == 0)]);

[90 72]


In [ ]:
## Find all the numbers that are not divisible by 7
print(a[a % 7 != 0]);


[12  4 89 81 87 93 29 13 27 67 43 17 22 90 46 12 51 50 65 72  4 38]


In [26]:
## Broadcasting for rules refer to the google collab notes or your python notes
## We will kickoff with the examples
a = np.arange(12).reshape(4,3);
b = np.arange(3);

print(a);
print(b);

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]


In [27]:
print(a + b);

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [30]:
a = np.arange(12).reshape(3,4);
b = np.arange(3);
print(a);
print(b);

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


In [31]:
print(a + b);

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 