In [2]:
import numpy as np;
a1 = np.arange(10);
a2 = np.arange(12).reshape(3,4);
a3 = np.arange(8).reshape(2,2,2);
print(a1 , a2 , a3);

[0 1 2 3 4 5 6 7 8 9] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
print(a2);

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
print(a2[1,3]);
print(a2[1][2]);
## In either of the ways we can access the elements it does not matter which one we are using
print(a2[-1,-1]);
print(a2[-1,0]);

7
6
11
8


In [5]:
print(a3);

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
print(a3[0,0,0]);
print(a3[0,0,1]);
print(a3[1,1,0]);

0
1
12


In [7]:
## Previously with using indexing we were able to only get 1 particular element
## But now with using slicing we can get multiple elements simultaneously
print(a1);

[0 1 2 3 4 5 6 7 8 9]


In [8]:
print(a1[0:5]);
print(a1[0:5:2]);

[0 1 2 3 4]
[0 2 4]


In [9]:
print(a2);

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
##Printing 0th column
print(a2[:,0]);
## Printing 0th row
print(a2[0,:]);
## Printing all the corner elements
print(a2[::2,::3]);
print(a2[::2,1::2]);
print(a2[1::2,::3]);
print(a2[:2,1::]);

[0 4 8]
[0 1 2 3]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[[4 7]]
[[1 2 3]
 [5 6 7]]


In [11]:
print(a3);

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [12]:
a3 = np.arange(27).reshape(3,3,3);
print(a3);

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [13]:
print(a3[1,:,1]);
print(a3[2,1:,1:]);
print(a3[::2,0,::2]);

[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


In [14]:
## Iterating on the numpy array
for i in a1:
    print(a1[i]);

0
1
2
3
4
5
6
7
8
9


In [15]:
for i in a2:
    print(i);

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [16]:
for i in a3:
    print(i);

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [17]:
## The above mentioned are the general methods we use in the Python also there is a function in the
## numpy library but we print them separately on the new line
for i in np.nditer(a3):
    print(i);


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [18]:
## Finding the transpose of the matrix
print(np.transpose(a2));

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [19]:
## There is a function called ravel invoked on the numpy array it converts the numpy array of n dim into the 1d array
print(a2.ravel());
print(a3.ravel());

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [20]:
## Horizontal Stacking combining two matrices of same shape(size) horizontally so only cols increase no of rows remains the same
a = np.arange(8).reshape(2,4);
b = np.random.random((2,4));
b = b.astype(np.int32);
c = np.hstack((a,b));
print(c);
print(np.hsplit(c , 4));## After stacking if we wanted to split at any point of time we can do that so it in any equal no of parts

[[0 1 2 3 0 0 0 0]
 [4 5 6 7 0 0 0 0]]
[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]]), array([[0, 0],
       [0, 0]]), array([[0, 0],
       [0, 0]])]


In [21]:
## Vertical Stacking is completely the opposite of horizontal stacking
a = np.arange(8).reshape(2,4);
b = np.random.random((2,4));
b = b.astype(np.int32);
c = np.vstack((a,b));
print(c);
print(np.vsplit(c , 2));

[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]
 [0 0 0 0]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[0, 0, 0, 0],
       [0, 0, 0, 0]])]
