In [ ]:
##Array operations
import numpy as np;
a1 = np.arange(12).reshape(3,4);
a2 = np.arange(12,24).reshape(3,4);


## We will do scalar operations and vector operations

In [2]:
## Scalar operations
import numpy as np;
a1 = np.arange(12).reshape(3,4);
a2 = np.arange(12,24).reshape(3,4);

print(a1 + 2);
print(a1 * 2);
print(a1 / 2);
print(a1 ** 2);

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [4]:
## Relational operations
import numpy as np;
a1 = np.arange(12).reshape(3,4);
a2 = np.arange(12,24).reshape(3,4);

print(a2 > 100);
print(a2 < 20);

[[False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]


In [6]:
import numpy as np;
a1 = np.arange(12).reshape(3,4);
a2 = np.arange(12,24).reshape(3,4);

## Vector operations if dimensions of the array are same we can directly add
print(a1 + a2);
print(a1 / a2);

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [ ]:
## Functions to do the mathematical operations we dont need to do anything

import numpy as np;
a1 = np.arange(12).reshape(3,4);
a2 = np.arange(12,24).reshape(3,4);
## for finding the max number in the numpy array we use np.max function
print(np.max(a2));
## Similarly there is the min number in the numpy array we use np.min function
print(np.min(a2));
## Here we can even find the max and min in each row and col
## for row -> 1 , col -> 0
print(np.max(a2 , axis = 1));

23
12
[15 19 23]


In [14]:
## Statistical related operations
import numpy as np;
a1 = np.arange(12).reshape(3,4);
a2 = np.arange(12,24).reshape(3,4);
print(np.mean(a2));
print(np.median(a2));
print(np.std(a2));
print(np.var(a2));

17.5
17.5
3.452052529534663
11.916666666666666


In [15]:
## Trigonometric functions

import numpy as np;
a1 = np.arange(12).reshape(3,4);
a2 = np.arange(12,24).reshape(3,4);

np.sin(a1);
np.cos(a2);

In [18]:
## Dot product(We find the dot product between the 2 matrices(a,b & b,c) then dimension of matrix is a,c)
import numpy as np;
a1 = np.arange(12).reshape(3,4);
a2 = np.arange(12,24).reshape(3,4);
a3 = np.arange(24,36).reshape(4,3);

print(np.dot(a3,a2));


[[1208 1283 1358 1433]
 [1352 1436 1520 1604]
 [1496 1589 1682 1775]
 [1640 1742 1844 1946]]


In [23]:
## Log and exponents
import numpy as np;
a1 = np.arange(12).reshape(3,4);
a2 = np.arange(12,24).reshape(3,4);

print(np.log(a2));
print(np.exp(a2));

[[2.48490665 2.56494936 2.63905733 2.7080502 ]
 [2.77258872 2.83321334 2.89037176 2.94443898]
 [2.99573227 3.04452244 3.09104245 3.13549422]]
[[1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06]
 [8.88611052e+06 2.41549528e+07 6.56599691e+07 1.78482301e+08]
 [4.85165195e+08 1.31881573e+09 3.58491285e+09 9.74480345e+09]]


In [27]:
## Round , floor and ceil functions
print(np.round(np.random.random((3,4))*100));
print(np.floor(np.random.random((3,4))*100));
print(np.ceil(np.random.random((3,4))*100));

[[13. 65. 27. 72.]
 [61. 26. 92. 30.]
 [27. 91. 56. 13.]]
[[59. 67. 65. 25.]
 [38. 44. 15. 57.]
 [29. 91. 41. 29.]]
[[48. 92. 80. 55.]
 [69. 30. 25. 62.]
 [ 8. 30. 48. 14.]]
