Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [19]:
## first we will create an empty array using np.empty(10); then put np.nan into it
## One of the very good question
import numpy as np;
a = np.nan * np.empty(10);
a[4] = 1;
print(a);

[nan nan nan nan  1. nan nan nan nan nan]


Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [20]:
a = int(input("Enter a number : a"));
b = int(input("Enter a number : b"));
c = np.random.randint(1,100,a*b).reshape(a,b);
print(c);
print(np.mean(c));


ValueError: invalid literal for int() with base 10: ''

Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [ ]:
a = int(input("Enter the value of a :"));
b = int(input("Enter the value of b :"));
c = np.zeros((a,b));
def ansfn(a,b):
    c[0,:] = 1;
    c[a-1,:] = 1;
    c[:,0] = 1;
    c[:,b-1] = 1;
ansfn(a,b);
print(c);


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [ ]:
# a = np.linspace(0,1,10);
## print(a); ## This will give me the wrong ans instead of doing this what i should do is

a = np.linspace(0,1,12)[1:10]
print(a);


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182]


Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
a = np.identity(3,4);
## This gives an error because for identity matrix the row and cols should be same
## So, not possible

TypeError: Cannot interpret '4' as a data type

Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
a = np.zeros((5,5));
b = np.random.randint(0,4,25).reshape(5,5);
c = a + b;## Here broadcasting takes place and the matrix we get is 5,5 matrix b before addition and then addition takes place
print(a);
print(b);
print(c);

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 1 0 3]
 [1 1 1 1 3]
 [3 3 1 3 0]
 [2 3 0 1 3]
 [3 2 0 1 2]]
[[0. 0. 1. 0. 3.]
 [1. 1. 1. 1. 3.]
 [3. 3. 1. 3. 0.]
 [2. 3. 0. 1. 3.]
 [3. 2. 0. 1. 2.]]


Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

In [26]:
a = np.random.randint(1,100,20).reshape(10,2);
point = np.array([2,3]);
print(a);
print(point);
def distance(coordinates,point):
    darray = np.array([]);
    darray = np.append(darray,np.sqrt(np.sum((coordinates-point)**2 , axis = 1)));
    return darray.astype(np.int32);
print(distance(a,point));

[[ 2 40]
 [30 42]
 [73 24]
 [77 62]
 [51 82]
 [69 95]
 [70 80]
 [35 71]
 [57 44]
 [ 9 40]]
[2 3]
[ 37  48  74  95  92 113 102  75  68  37]


Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
a = np.arange(1,337).reshape(6,7,8);

