In [94]:
import numpy as np;
a = np.random.randint(1,24,100);

print(a);
print(np.sort(a));

[11 18 21  2 11  8  8  9 14 19  9  7  2  9  5 20 13 15 11  3  9  2  3  1
 12  5 23  9  8 16  1 12  6 12  3  3 18 16 17  1 20 12  7  6  6  4  5  2
 17 15 17 16 22  9  2  4 23 11 23  3  3 16 20  4  4  7  9  6  5 13  4  9
 19 16  9  5 15  4  4 20  7 17  6 20 23  5  5 13  7 11  7 14  1 20 16 13
  3 21 17  2]
[ 1  1  1  1  2  2  2  2  2  2  3  3  3  3  3  3  3  4  4  4  4  4  4  4
  5  5  5  5  5  5  5  6  6  6  6  6  7  7  7  7  7  7  8  8  8  9  9  9
  9  9  9  9  9  9 11 11 11 11 11 12 12 12 12 13 13 13 13 14 14 15 15 15
 16 16 16 16 16 16 17 17 17 17 17 18 18 19 19 20 20 20 20 20 20 21 21 22
 23 23 23 23]


In [95]:
b = np.random.randint(1,100,24).reshape(6,4);
print(b);
print(np.sort(b));## Here it does row wise sorting
print(np.sort(b,axis = 0));## Here it does column wise sorting
##But to sort in the descending order




[[18 99 11 13]
 [23 73 53  1]
 [41 52  5 66]
 [56 46 51 85]
 [60 13 25 82]
 [ 4 88 73 23]]
[[11 13 18 99]
 [ 1 23 53 73]
 [ 5 41 52 66]
 [46 51 56 85]
 [13 25 60 82]
 [ 4 23 73 88]]
[[ 4 13  5  1]
 [18 46 11 13]
 [23 52 25 23]
 [41 73 51 66]
 [56 88 53 82]
 [60 99 73 85]]


In [96]:
## Previously we had used hstack and vstack functions for stacking the 2 matrices
## Instead of that we could even use concatenate method
c = np.arange(0,6).reshape(2,3);
d = np.arange(6,12).reshape(2,3);

print(np.concatenate((c,d), axis=0));
print(np.concatenate((c,d), axis=1));

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [97]:
## Finding the unique elements in the numpy array;

a = np.array([1,1,2,1,1,2]);
print(np.unique(a));

[1 2]


In [98]:
## For expanding the dimensions for some use cases we will learn about them later is np.expand_dims;

a = np.arange(6);
print(a);
print(np.expand_dims(a , axis = 0));
print(np.expand_dims(a , axis = 1));

[0 1 2 3 4 5]
[[0 1 2 3 4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [99]:
# Previously we had dealt of how to find the out those elements which satisfying the given condition using the relational operator
## But if we wanted to find out the positions the items which satisfy the condition we use np.where() function

a = np.arange(1,21).reshape(5,4);
print(a);
print(np.where(a > 10));
a[np.where(a > 10)] = 10;
print(a);

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
(array([2, 2, 3, 3, 3, 3, 4, 4, 4, 4]), array([2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [100]:
## Other way of replacing is 
print(a);
## Syntax is np.where(condn , if condn true what it should be replaced, if false what it should be replaced)
print(np.where(a>5 , 10, a));
print(np.where(a % 2 == 0, 0,a));

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[ 1  2  3  4]
 [ 5 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[1 0 3 0]
 [5 0 7 0]
 [9 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [101]:
## Finding out the max element in the rows and columns for n dim arrays is using np.argmax;
print(a);
print(np.argmax(a));## Here it directly gives of the highest element in the matrix
print(np.argmax(a,axis = 0));## Here it directly gives of the highest element in each row
print(np.argmax(a,axis = 1)); ## here it directly gives of the highest element in each column


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
9
[3 2 2 2]
[3 3 1 0 0]


In [102]:
a = np.arange(10);
b = np.arange(0,10).reshape(2,5);
print(a);
print(b);
##Here if we want to find the cummulative sum that is the total upto that point of time

print(np.cumsum(a));
print(np.cumsum(b,axis=1));## Along the column
print(np.cumsum(b,axis=0));## Along the row

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 0  1  3  6 10 15 21 28 36 45]
[[ 0  1  3  6 10]
 [ 5 11 18 26 35]]
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]]


In [103]:
## Similarly we could do the same for the Cummulative Product as well
print(np.cumprod(a));
print(np.cumprod(b,axis = 1));##ALong column
print(np.cumprod(a, axis = 0));#Along row


[0 0 0 0 0 0 0 0 0 0]
[[    0     0     0     0     0]
 [    5    30   210  1680 15120]]
[0 0 0 0 0 0 0 0 0 0]


In [104]:
a = np.random.randint(1,100,200);
print(a);
print(np.percentile(a , 100));
print(np.percentile(a , 50));
print(np.percentile(a , 37.88));
print(np.percentile(a , 0));

[36 60 32 48 90  7 43 27 58 19 27 88  6 95 26 67 52 67 19  9 38 40 44 68
 27 32 13 12 28 80 90 87 40 39 77 77 58 52 75  9 61 47 90 54 82 75 51 65
 53 81 38 84  6 87 53 92 24 43 91 45 22 13 31 31 19 53 81 11 76 26 62 21
 44  3 58 74 70  5 60 57 99  5 61 33 94 98  1 59 16 97 20 87  6 47 82 73
 14 65 67 95  1 34  9 20 48 97 65 11 54 53 13  4 92 52 47 49 53 42 42 36
 32 36 18 25 95  8 77 28 87 76 67 84 34 92 29 95 99 92 23 12 47 95 94  4
 63 37 82 11 80 12 88 95 94 33 85  2  3 76 19 17 15 90 26 33  1 56 32 51
 34 63 27 13 87 54 82 33 90 65 81 70 89 40  1 53 63 96 65 50 57  4 97 74
  8 27 84 77 33 41 44 19]
99.0
50.5
36.38120000000001
1.0


In [105]:
print(np.histogram(a , bins = [0,10,20,30,40,50,60,70,80,90,100]));

(array([21, 20, 18, 21, 19, 22, 18, 14, 21, 26]), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


In [106]:
## Corelation coeffiecient is the value b/w -1 to 1 which says that if it is 1 the 2 quantities rise with the same amount
## If it is 0 both quantities does not have any corelation between them
## If it is -1 if one quantity increases with some amount the other quantity decreases with the same amount
salaryUSD = np.random.randint(10,100,20);
experienceYrs = np.random.randint(1,10,20);
print(salaryUSD);
print(experienceYrs);
print(np.corrcoef(salaryUSD,experienceYrs));## SO we could say on getting 1 year of experience we could get a salary hike of 0.12%


[61 86 77 54 40 49 98 80 37 10 51 58 22 69 75 12 75 49 49 89]
[5 3 5 5 7 9 2 5 6 7 1 4 9 6 8 3 8 7 5 4]
[[ 1.         -0.30063651]
 [-0.30063651  1.        ]]


In [107]:
## IN multiple arrays if we wanted to check whether we have common elements or not we use np.isin();
a = np.random.randint(1,10,20);
b = np.arange(1,21);
print(a);
print(b);
print(np.isin(a,b));## It gives us the boolean values of a array ;
print(np.isin(b,a));
print(b[np.isin(b,a)]);## These are the values that are common in both the arrays

[8 9 5 3 2 3 3 2 3 3 4 5 7 8 6 3 4 3 9 4]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[False  True  True  True  True  True  True  True  True False False False
 False False False False False False False False]
[2 3 4 5 6 7 8 9]


In [108]:
## For flipping the array we generally use the np.flip();
print(a);
print(np.flip(a));
## One such use case we can use this for sorting in decreasing order
print(np.flip(np.sort(a)));



[8 9 5 3 2 3 3 2 3 3 4 5 7 8 6 3 4 3 9 4]
[4 9 3 4 3 6 8 7 5 4 3 3 2 3 3 2 3 5 9 8]
[9 9 8 8 7 6 5 5 4 4 4 3 3 3 3 3 3 3 2 2]


In [109]:
## Working with flip in 2d
c = a.reshape(4,5);
print(c);
print(np.flip(c));
print(np.flip(c,axis=0));## Row wise
print(np.flip(c,axis = 1)); ## Col wise flip

[[8 9 5 3 2]
 [3 3 2 3 3]
 [4 5 7 8 6]
 [3 4 3 9 4]]
[[4 9 3 4 3]
 [6 8 7 5 4]
 [3 3 2 3 3]
 [2 3 5 9 8]]
[[3 4 3 9 4]
 [4 5 7 8 6]
 [3 3 2 3 3]
 [8 9 5 3 2]]
[[2 3 5 9 8]
 [3 3 2 3 3]
 [6 8 7 5 4]
 [4 9 3 4 3]]


In [110]:
# If we want to modify the Numpy Array using function then it is np.put(array,[index],[values u want to change])
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,13,423]);
np.put(a,[1,4],[100,122]);
print(a);

[  1 100   3   4 122   6   7   8   9  10  11  12  13  13 423]


In [114]:
# Deleting the values
a = np.delete(a,[0,1,2]);
print(a);

[  4 122   6   7   8   9  10  11  12  13  13 423]


In [ ]:
## Now we will see all the set functions that we had seen so far in Sets in Python
a = np.arange(1,10);
b = np.arange(1,20);
print(np.union1d(a,b));
print(np.intersect1d(a,b));
print(np.setdiff1d(a,b));
print(np.setxor1d(a,b));
print(np.in1d(10,a));## It is better to use np.isin() than in1d() function

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4 5 6 7 8 9]
[]
[10 11 12 13 14 15 16 17 18 19]
[False]


C:\Users\Laptop\AppData\Local\Temp\ipykernel_7700\164797722.py:8: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(10,a));


In [124]:
## Mapping of the given array with few of the numbers in our range to do some specific operation which we will deal with it in deep learning
print(a);
b = np.clip(a,a_min=25,a_max=100)
print(np.clip(b));

[1 2 3 4 5 6 7 8 9]
[25 25 25 25 25 25 25 25 25]
