In [2]:
import numpy as np;

a = np.array([1,2,3,4,5]);
print(a);
print(type(a));


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
##Creating 2d and 3d numpy arrays
##2d arrays are created using passing 2d lists inside numpy arrays
import numpy as np;
a = np.array([[1,2,3],[12,13,14]]);
print(a);
## in the same way we could create for 3d arrays as well
b = np.array([[1,2,3],[4,5,6],[7,8,9]]);
print(b);
print(type(a));


[[ 1  2  3]
 [12 13 14]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [4]:
## Setting the datatype of the elements in the numpy array
import numpy as np;
a = np.array([1,2,4232.23], dtype = complex);
print(a);

[1.00000e+00+0.j 2.00000e+00+0.j 4.23223e+03+0.j]


In [5]:
## Range arrays just like the range function
a = np.arange(1,11);
print(a)
b = np.arange(1,11,2);
print(b);

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [6]:
## Other ways of initilizing the array
import numpy as np;
a = np.ones((3,4));## Here we need to pass the tuple not the array of size 
print(a);
b = np.zeros((2,5));
print(b);

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
##Using the random function in numpy packages
import numpy as np;
a = np.random.random([1,2,3]);
print(a);

[[[0.3699279  0.56712316 0.63106744]
  [0.73762429 0.08496657 0.51802771]]]


In [8]:
### Using linspace 
import numpy as np;
a = np.linspace(1,10,4);
print(a);

[ 1.  4.  7. 10.]


In [9]:
## Creating an identity matrix
import numpy as np;
a = np.identity(10);
print(a);

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [14]:
a = np.array([[1,2,3],[4,5,6]]);
print(a.shape);
print(a.shape[0]);
print(a.shape[1]);

(2, 3)
2
3
